### PR TITLE
Export facebooktemplate

### PR DESCRIPTION
**Pull request by nbransby**

### CODE REVIEW

**Comment by nbransby** [comment]
I need this base class exported to simplify a lot of dialogue-builder code: https://github.com/nbransby/dialogue-builder/search?utf8=%E2%9C%93&q=FacebookTemplate

**Comment by stojanovic** [comment]
Hm, ok, we can do it, but let's find a better name, `import FacebookTemplate = builder.fbTemplate.FacebookTemplate` looks confusing.
Any suggestions? Maybe BaseTemplate or something like that?

**Comment by nbransby** [comment]
Or just Template?

Or MessageTemplate:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/templates

**Comment by stojanovic** [comment]
Yeah, but `new fbTemplate.Template()` looks a bit weird, `new fbTemplate.BaseTemplate()` or `new fbTemplate.MessageTemplate()` is better I guess. Because it is a base template that everything else extends.

**Comment by stojanovic** [comment]
Closing this because of inactivity, feel free to reopen and fix the name or I'll do that at some point.

**Pull request closed without merging**
