### PR TITLE
Fix warning returned by send api due to extranous property in request json

### PR DESCRIPTION
**Pull request by nbransby**

### CODE REVIEW

**Comment by gojko** [comment]
It would be good if you could also add an automated test for this before merging, so we can make sure not to break this functionality when someone else is modifying the code in the future.

**Comment by nbransby** [comment]
I looked at adding a test for this one but its actually quite tricky to implement - I thought I would get this PR in first as its currently broken

**Comment by stojanovic** [comment]
It's not tricky, just check that json in the end doesn't have `notification_type` property.

**Comment by nbransby** [comment]
Which spec is doing something similar so I can see an example?

**Comment by stojanovic** [comment]
Something like [this](https://github.com/nbransby/claudia-bot-builder/blob/8b706e9bfee8075fc8d2a5653d7731d48893e19a/spec/facebook/facebook-reply-spec.js#L100-L116), just `notification_type` in message and make sure it doesn't exists in message.

**Comment by stojanovic** [comment]
Merging it right now and I'll add the test later today and publish new version.

**Comment by nbransby** [comment]
Sorry chaps didnt get a chance write the test - let me know if you still need me to do it

**Pull request merged**
