### PR TITLE
catch messaging_referrals in fb/parse

### PR DESCRIPTION
**Pull request by yipcma**
this branch is edited from tag v2.15 intended to catch fb/messaging_referrals.
- it catches all types of referrals, and put referral.ref in request.text when possible
- it adds a referral boolean
- it is placed ahead of other condition checks to not get hidden

Thank you very much for the wonderful and hackable project :)

### CODE REVIEW

**Comment by gojko** [comment]
hi, thanks for this - can you please add some examples of referral messages and correct parsing to https://github.com/claudiajs/claudia-bot-builder/blob/master/spec/facebook/facebook-parse-spec.js, so future changes don't break your code?

**Comment by yipcma** [comment]
Sure thing @gojko, am new to testing, any best references you would point me to so I can get up to speed?

**Comment by gojko** [comment]
@yipcma check out https://github.com/claudiajs/claudia-bot-builder/blob/master/CONTRIBUTING.md#running-tests for how to run tests, and then I guess reading existing tests for the bot builder is a good start. Check out https://jasmine.github.io/ for info on the testing automation tool we use

**Comment by gojko** [comment]
I'm closing this due to inactivity. If someone wants to pick this up, please re-open the pull request or submit a new one

**Pull request closed without merging**
