### PR TITLE
Skype format message

### PR DESCRIPTION
**Pull request by IvanJov**
Please review the code!

I would like to finish remaining tasks bellow before merging.
- [x]  Write documentation
- [ ] Check if it's possible to send Hero, Thumbnail and Receipt without Carousel in V3 and implement it
- [ ] Check if it's still possible to send Photo as URL, without converting it to base64

### CODE REVIEW

**Comment by stojanovic** [comment]
Seem good so far, just a question, is any info required for Hero, Thumbnail and Receipt?
Not sure I like this structure:
```js
.addHero(title, subtitle, text, images)
```
if nothing is required, because this doesn't look that nice:
```js
.addHero(null, null, null, [imageUrl])
```
if only images are required I would prefer:
```js
.addHero(images, title, subtitle, text)
```
or even:
```js
.addHero(images, text)
  .addTitle(title)
  .addSubtitle(subtitle)
```

**Comment by IvanJov** [comment]
@stojanovic Nothing is required for Hero, Thumbnail and Receipt. I like the idea for addTitle and addSubtitle functions.

What do you think about passing and object with title, subtitle, text and image to addHero (or other) function?

**Comment by stojanovic** [comment]
We already have something like `.addTitle` in [FB templates](https://github.com/claudiajs/claudia-bot-builder/blob/master/lib/facebook/format-message.js#L435-L444)

Object works too

**Comment by IvanJov** [comment]
@stojanovic Ok, I am going with functions!

**Comment by IvanJov** [comment]
This is fixed. I will write documentation and this can probably be merged. I will work later on the remaining two points I posted above.

**Comment by IvanJov** [comment]
@stojanovic Just wrote documentation. Please let me know if you think that something is missing. I will keep updating working on the Skype format messages, need to check two remaining stuffs I wrote above, but for now I think that this is ready for merge.

I've tested all methods in Skype bot.

**Comment by stojanovic** [comment]
Cool, thanks!

**Pull request merged**
